apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqlinstances.mysql.example.com
spec:
  group: dipto.mysql.example
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: mysqlinstances
    singular: mysqlinstance
    kind: MySQLInstance
