---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dipto.mysql.example.dipto.mysql.example
  resources:
  - mysqlinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dipto.mysql.example.dipto.mysql.example
  resources:
  - mysqlinstances/finalizers
  verbs:
  - update
- apiGroups:
  - dipto.mysql.example.dipto.mysql.example
  resources:
  - mysqlinstances/status
  verbs:
  - get
  - patch
  - update
