apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysqlsvc
  name: mysqlsvc
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysqlsvc
  type: ClusterIP